### ISSUE TITLE
DLL References is not found

### ISSUE THREAD

**Issue by icharge** [montyaahad/RestaurantBillingSystem#1]
This project requires some DLLs of Components.
Please upload them to project.

**Comment by montyaahad** [comment]
can you be more specific? All dlls are included in RestaurantBillingSystem/RestaurantManagement/Library folder. 
There was no database scripts in repository. I've uploaded them. Please make sure you have MS SQL server 2005 (/2008/2012) installed and run those scripts. Thanks.

**Comment by icharge** [comment]
Some of Krypton's Dlls.
I guess it use for form control.

**Comment by montyaahad** [comment]
Hi icharge,
sorry. I forgot to add some dlls of krypton. I've added these on library folder, also updated the project. Please get latest code and check. Its working fine now. Thanks

**Comment by icharge** [comment]
I interested this project. And studying about system like this.
Anyway thank you for respond my message and for help.

**Comment by montyaahad** [comment]
I'll be glad if it helps someone. Thanks. I'm closing the issue.
